//Copyright 2020 Onegini B.V.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

package util

import (
  "testing"
  "net/url"
)

// example AndroidManifest generated by Onegini Cordova Plugin 4.2+
const manifestWithOneginiIntentFilter string = `<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.onegini.martin" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:label="OneginiRedirectionIntent" android:name="OneginiRedirectionIntent">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="cordovaexample" android:host="login-success" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

// example AndroidManifest generated by Onegini Cordova Plugin 4.1 or older
const manifestWithOldOneginiIntentFilter string = `<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.onegini.martin" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="cordovaexample" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

const manifestWithHttpsOneginiIntentFilter string = `<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.onegini.martin" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:label="OneginiRedirectionIntent" android:name="OneginiRedirectionIntent">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="www.cordova.example.com" android:pathPrefix="/login-success" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

const manifestWithoutOneginiIntent string = `<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.onegini.martin" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

///////////////////////////////////////////////////////////////
// WHEN ANDROID MANIFEST DOESN'T CONTAIN ONEGINI INTENT FILTER
//////////////////////////////////////////////////////////////

// should not modify manifests when there are no Onegini IntentFilters found inside
func TestReplaceManifestNotModifyManifest(t *testing.T) {
  testSuit := []struct {
		manifest string
		shouldRemove bool
		expectedResult string
	}{
		{"", false, ""},
    {"", true, ""},
		{manifestWithoutOneginiIntent, false, manifestWithoutOneginiIntent},
    {manifestWithoutOneginiIntent, true, manifestWithoutOneginiIntent},
	}
  url, _ := url.Parse("onegini://loginsuccess")

	for _, testCase := range testSuit {
		result := ReplaceManifest(testCase.manifest, testCase.shouldRemove, url)
		if result != testCase.expectedResult {
			t.Errorf("Should not modify manifest, before was:\n\n %v\n\n, after:\n\n %v\n\n", testCase.manifest, result)
		}
	}
}

////////////////////////////////////////////////////////////
// WHEN ANDROID MANIFEST CONTAINS OLD ONEGINI INTENT FILTER
////////////////////////////////////////////////////////////

// should ignore "remove intent" option and override the old intent anyway
// old cordova plugin version didn't support custom registration so there is no use case for removing intent
func TestReplaceManifestReplaceOldIntentFilterWithCustomIntentFilter(t *testing.T) {
  expectedManifest := `<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.onegini.martin" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="onegini" android:host="loginsuccess" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

  url, _ := url.Parse("onegini://loginsuccess")

  result := ReplaceManifest(manifestWithOldOneginiIntentFilter, false, url)
  if result != expectedManifest {
      t.Errorf("Incorrect result, the manifest should contain new scheme 'onegini://loginsuccess':\n%v", result)
  }

  result2 := ReplaceManifest(manifestWithOldOneginiIntentFilter, true, url)
  if result2 != expectedManifest {
      t.Errorf("Incorrect result, the manifest should contain new scheme 'onegini://loginsuccess':\n%v", result2)
  }
}

///////////////////////////////////////////////////////////////////////////////
// WHEN ANDROID MANIFEST CONTAINS NEW ONEGINI INTENT FILTER WITH CUSTOM SCHEME
///////////////////////////////////////////////////////////////////////////////

// should remove new Onegini IntentFilter when requested
func TestReplaceManifestRemoveCustomIntentFilter(t *testing.T) {
  url, _ := url.Parse("onegini://loginsuccess")

  result := ReplaceManifest(manifestWithOneginiIntentFilter, true, url)
  if result != manifestWithoutOneginiIntent {
      t.Errorf("Incorrect result, the manifest should not contain Onegini IntentFilter:\n%v", result)
  }
}

// should replace with custom Onegini IntentFilter when requested
func TestReplaceManifestReplaceCustomIntentFilterWithCustomIntent(t *testing.T) {
  expectedManifest := `<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.onegini.martin" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:label="OneginiRedirectionIntent" android:name="OneginiRedirectionIntent">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="onegini" android:host="loginsuccess" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

  url, _ := url.Parse("onegini://loginsuccess")
  result := ReplaceManifest(manifestWithOneginiIntentFilter, false, url)
  if result != expectedManifest {
      t.Errorf("Incorrect result, the manifest should contain new scheme 'onegini://loginsuccess':\n%v", result)
  }
}

// should replace with Https Onegini IntentFilter when requested
func TestReplaceManifestReplaceCustomIntentFilterWithHttpIntentFilter(t *testing.T) {
  expectedManifest := `<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.onegini.martin" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:label="OneginiRedirectionIntent" android:name="OneginiRedirectionIntent">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="www.onegini.com" android:pathPrefix="/loginsuccess" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

  url, _ := url.Parse("https://www.onegini.com/loginsuccess")
  result := ReplaceManifest(manifestWithOneginiIntentFilter, false, url)
  if result != expectedManifest {
      t.Errorf("Incorrect result, the manifest should contain new scheme 'https://www.onegini.com/loginsuccess':\n%v", result)
  }
}

///////////////////////////////////////////////////////////////////////////////
// WHEN ANDROID MANIFEST CONTAINS NEW ONEGINI INTENT FILTER WITH HTTPS SCHEME
///////////////////////////////////////////////////////////////////////////////

// should remove Https Onegini IntentFilter when requested
func TestReplaceManifestRemoveIntentFilter(t *testing.T) {
  url, _ := url.Parse("onegini://loginsuccess")

  result := ReplaceManifest(manifestWithHttpsOneginiIntentFilter, true, url)
  if result != manifestWithoutOneginiIntent {
      t.Errorf("Incorrect result, the manifest should not contain Onegini IntentFilter:\n%v", result)
  }
}

// should replace with custom Onegini IntentFilter when requested
func TestReplaceManifestReplaceHttpsIntentFilterWithCustomIntent(t *testing.T) {
  expectedManifest := `<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.onegini.martin" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:label="OneginiRedirectionIntent" android:name="OneginiRedirectionIntent">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="onegini" android:host="loginsuccess" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

  url, _ := url.Parse("onegini://loginsuccess")
  result := ReplaceManifest(manifestWithHttpsOneginiIntentFilter, false, url)
  if result != expectedManifest {
      t.Errorf("Incorrect result, the manifest should contain new scheme 'onegini://loginsuccess':\n%v", result)
  }
}

// should replace with Https Onegini IntentFilter when requested
func TestReplaceManifestReplaceHttpsIntentFilterWithHttpIntentFilter(t *testing.T) {
  expectedManifest := `<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.onegini.martin" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:label="OneginiRedirectionIntent" android:name="OneginiRedirectionIntent">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="www.onegini.com" android:pathPrefix="/loginsuccess" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

  url, _ := url.Parse("https://www.onegini.com/loginsuccess")
  result := ReplaceManifest(manifestWithHttpsOneginiIntentFilter, false, url)
  if result != expectedManifest {
      t.Errorf("Incorrect result, the manifest should contain new scheme 'https://onegini.com/loginsuccess':\n%v", result)
  }
}
