#import "OneginiConfigModel.h"

@implementation OneginiConfigModel

// Config model generated by SDK Configurator version: CONFIGURATOR_VERSION

+ (NSArray *)certificates
{
    return @[@""]; //Base64Certificates
}

+ (NSDictionary *)configuration
{
    return @{
             @"ONGAppIdentifier" : @"",
             @"ONGAppPlatform" : @"ios",
             @"ONGAppVersion" : @"",
             @"ONGAppBaseURL" : @"",
             @"ONGResourceBaseURL" : @"",
             @"ONGRedirectURL" : @"",
             };
}

+ (NSString *)serverPublicKey
{
    return @"";
}


@end