package com.onegini.mobile.sdk.android

import android.os.Build
import com.onegini.mobile.sdk.android.model.OneginiClientConfigModel

class OneginiConfigModel {
  /* Config model generated by SDK Configurator version: CONFIGURATOR_VERSION */
  val appIdentifier = "value_will_be_replaced" 
  val appPlatform = "android"
  val redirectionUri = "value_will_be_replaced"
  val appVersion = "value_will_be_replaced"
  val baseURL = "value_will_be_replaced"
  val resourceBaseURL = "value_will_be_replaced"
  val keystoreHash = "value_will_be_replaced"
  val maxPinFailures = 1
  val serverPublicKey: String? = null
  val serverType = "value_will_be_replaced"
  val serverVersion = "value_will_be_replaced"
 
  override fun toString(): String {
    return "ConfigModel{" +
        "  appIdentifier='" + appIdentifier + "'" +
        ", appPlatform='" + appPlatform + "'" +
        ", redirectionUri='" + redirectionUri + "'" +
        ", appVersion='" + appVersion + "'" +
        ", baseURL='" + baseURL + "'" +
        ", maxPinFailures='" + maxPinFailures + "'" +
        ", resourceBaseURL='" + resourceBaseURL + "'" +
        ", keyStoreHash='" + keyStoreHash + "'" +
        ", serverPublicKey='" + serverPublicKey + "'" +
        ", serverType='" + serverType + "'" +
        ", serverVersion='" + serverVersion + "'" +
        "}"
  }
}
