// Code generated by go-bindata.
// sources:
// lib/OneginiConfigModel.h
// lib/OneginiConfigModel.java
// lib/OneginiConfigModel.m
// lib/addFileToXcodeProject.rb
// lib/bcprov-jdk15on-1.46.jar
// lib/removeFileFromXcodeProject.rb
// DO NOT EDIT!

package data

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// libOneginiconfigmodelH reads file data from disk. It returns an error on failure.
func libOneginiconfigmodelH() (*asset, error) {
	path := "/Users/jim/go/src/github.com/Onegini/onegini-sdk-configurator/lib/OneginiConfigModel.h"
	name := "lib/OneginiConfigModel.h"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libOneginiconfigmodelJava reads file data from disk. It returns an error on failure.
func libOneginiconfigmodelJava() (*asset, error) {
	path := "/Users/jim/go/src/github.com/Onegini/onegini-sdk-configurator/lib/OneginiConfigModel.java"
	name := "lib/OneginiConfigModel.java"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libOneginiconfigmodelM reads file data from disk. It returns an error on failure.
func libOneginiconfigmodelM() (*asset, error) {
	path := "/Users/jim/go/src/github.com/Onegini/onegini-sdk-configurator/lib/OneginiConfigModel.m"
	name := "lib/OneginiConfigModel.m"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libAddfiletoxcodeprojectRb reads file data from disk. It returns an error on failure.
func libAddfiletoxcodeprojectRb() (*asset, error) {
	path := "/Users/jim/go/src/github.com/Onegini/onegini-sdk-configurator/lib/addFileToXcodeProject.rb"
	name := "lib/addFileToXcodeProject.rb"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libBcprovJdk15on146Jar reads file data from disk. It returns an error on failure.
func libBcprovJdk15on146Jar() (*asset, error) {
	path := "/Users/jim/go/src/github.com/Onegini/onegini-sdk-configurator/lib/bcprov-jdk15on-1.46.jar"
	name := "lib/bcprov-jdk15on-1.46.jar"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libRemovefilefromxcodeprojectRb reads file data from disk. It returns an error on failure.
func libRemovefilefromxcodeprojectRb() (*asset, error) {
	path := "/Users/jim/go/src/github.com/Onegini/onegini-sdk-configurator/lib/removeFileFromXcodeProject.rb"
	name := "lib/removeFileFromXcodeProject.rb"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"lib/OneginiConfigModel.h":          libOneginiconfigmodelH,
	"lib/OneginiConfigModel.java":       libOneginiconfigmodelJava,
	"lib/OneginiConfigModel.m":          libOneginiconfigmodelM,
	"lib/addFileToXcodeProject.rb":      libAddfiletoxcodeprojectRb,
	"lib/bcprov-jdk15on-1.46.jar":       libBcprovJdk15on146Jar,
	"lib/removeFileFromXcodeProject.rb": libRemovefilefromxcodeprojectRb,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"lib": &bintree{nil, map[string]*bintree{
		"OneginiConfigModel.h":          &bintree{libOneginiconfigmodelH, map[string]*bintree{}},
		"OneginiConfigModel.java":       &bintree{libOneginiconfigmodelJava, map[string]*bintree{}},
		"OneginiConfigModel.m":          &bintree{libOneginiconfigmodelM, map[string]*bintree{}},
		"addFileToXcodeProject.rb":      &bintree{libAddfiletoxcodeprojectRb, map[string]*bintree{}},
		"bcprov-jdk15on-1.46.jar":       &bintree{libBcprovJdk15on146Jar, map[string]*bintree{}},
		"removeFileFromXcodeProject.rb": &bintree{libRemovefilefromxcodeprojectRb, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
